GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY4OTA2ODYxMH0.0IzUiu4G-k2KiVvvmP4RavoIGC4ZMlO6tl5dR7k2IMA.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY4OTA2ODU5NSwiZXhwIjoxNjg5MDY4NjEwfQ._8vwmvUjGJ9nQOnnk2JvjdHF0QzjF93MeU0Yb83jb4w.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY4OTA2ODU0OCwiZXhwIjoxNjg5MDY4NTYzfQ.2zsNJ65ekRbjHS9ZQAVsB1Do8zmBaYAhZjAOxttiiKQ.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY4OTA2ODUxOSwiZXhwIjoxNjg5MDY4NTM0fQ.OAh97TSIVquI0EjoMODbmLWIU4xMellR8heys5ALhBc.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY4OTA2ODM1NiwiZXhwIjoxNjg5MDY4MzcxfQ.MfOmul6eAgYnMEal5beWW9CRqoeKPgLFwBTBNX-ipgU
###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Kyle"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}